[package]
name = "Geni"
version = "1.0.0"
authors = []

[addresses]
geni = "_"

[dev-addresses]
geni = "0xCAFE"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
